services:
  pythonapp:
    build: ./python/
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - '5000:5000'
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'TourDeApp'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10